[package]
name = "tomltest"
version = "0.1.0"
authors = ["hartmut <hartmut.prochaska@gmail.com>"]

[dependencies]
serde = "*" # https://crates.io/crates/serde
serde_derive = "*" # https://crates.io/crates/serde_derive
toml = "*" # https://crates.io/crates/toml
